modules/pembelian/controllers/ReturPembelianController.php
<?php

namespace app\modules\pembelian\controllers;

use Yii;
use app\models\ReturPembelian;
use app\models\Pembelian;
use app\models\DetailPembelian;
use app\models\Mutasi;
use app\models\Barang;
use app\models\StokGudang;
use app\models\ReturPembelianSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

class ReturPembelianController extends Controller
{
	public $enableCsrfValidation = false;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
			'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','view','update'],
                'rules' => [
                    [
                        'allow' => false,
                        'actions' => [''],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index','create','view','update','delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
		// $privilage = Yii::$app->user->identity->privilage;
	    // if($privilage !== 1 && $privilage !== 3 && $privilage !== 5 ){
		    // throw new ForbiddenHttpException("Forbidden access");
	    // }
        $searchModel = new ReturPembelianSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->pagination->pageSize= 10;
		
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
		// $privilage = Yii::$app->user->identity->privilage;
	    // if($privilage !== 1 && $privilage !== 3 && $privilage !== 5 ){
		    // throw new ForbiddenHttpException("Forbidden access");
	    // }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
		// $privilage = Yii::$app->user->identity->privilage;
	    // if($privilage !== 1 && $privilage !== 3 && $privilage !== 5 ){
		    // throw new ForbiddenHttpException("Forbidden access");
	    // }
        $model = new ReturPembelian();
		$returList = Pembelian::find()
			->where(['id' => -1]);
		$dataProvider = new ActiveDataProvider([
			'query' => $returList
		]);

        if ($model->load(Yii::$app->request->post())) {

			$noPembelian = Pembelian::find()
				->where(['no_faktur' => $model->no_faktur_pembelian])
				->one();

			$returList = DetailPembelian::find()
				->where(['id_pembelian' => $noPembelian->id]);



			$dataProvider = new ActiveDataProvider([
				'query' => $returList
			]);

			$model = new ReturPembelian();
				return $this->render('create', [
					'model' => $model,
					'dataProvider' => $dataProvider,

				]);


        } else {
			\Yii::$app->getSession()->setFlash('status', '');

            return $this->render('create', [
                'model' => $model,
				'dataProvider' => $dataProvider,

            ]);
        }
    }

    public function actionSave()
    {

        $data = [];
        $model = new ReturPembelian();
        $post = $_POST;
        $data['status'] = false;
		$gudangDefault = \app\models\Merchant::find()->one();
		
        for($i = 0; $i < count($post['id']); $i++){

            $model = new ReturPembelian();
            $model->id_pembelian = $post['id_pembelian'][$i];
            $model->id_gudang = $gudangDefault->id_gudang;
            $model->no_faktur_pembelian = $post['no_faktur'][$i];
            $model->tanggal_retur =date('Y-m-d', strtotime($post['tanggal_retur'])); //new \yii\db\Expression('NOW()');
            $model->id_barang = $post['idbarang'][$i];
            $model->jumlah = $post['jumlah'][$i];
            $model->harga_beli = $post['hb'][$i];
            $model->harga_kena_pajak = $post['hkp'][$i];
            $model->ppn = $post['ppn'][$i];
            $model->diskon = $post['diskon'][$i];
            $model->total = $post['totalhj'][$i];
            $model->tanggal = new \yii\db\Expression('NOW()');
            if($model->save()){
                $data['status'] = true;
				$data['nofaktur'] = $model->id_pembelian;
				$data['faktur'] = $model->no_faktur_pembelian;
				$data['tanggal'] = $post['tanggal_retur'];
                // update pembelian
				$pembelian = Pembelian::find()
					->where([
                       'id' => $post['id_pembelian'][$i],
                       'id_gudang' => $model->id_gudang,
					])
					->one();

				$pembelian->harga_kena_pajak -= $post['totalhj'][$i];
				$pembelian->sisa -= $post['totalhj'][$i];
				$pembelian->admin_id = Yii::$app->user->identity->id;
				$pembelian->save();

                $detail = DetailPembelian::find()
                    ->where([
                        'id_pembelian' => $post['id_pembelian'][$i],
                        'id_barang' => $post['idbarang'][$i]
                    ])
                    ->one();
                $stok = $detail->jumlah - $post['jumlah'][$i];
                $detail->jumlah = $stok;
                $detail->total = $stok * $detail->harga_kena_pajak;
				$detail->admin_id = Yii::$app->user->identity->id;
                $detail->save();

                $produk = StokGudang::find()
                    ->where([
                        'id_barang' => $post['idbarang'][$i],
                        'id_gudang' => $model->id_gudang,
                    ])
                    ->one();
					
				$findStok = Mutasi::find()
                    ->where([
                        'id_barang' => $post['idbarang'][$i],
						'id_gudang' => $pembelian->id_gudang,
                    ])
                    ->orderBy('tanggal desc')
					->orderBy('id desc')
                    ->one();
                $stokAwal = 0;
                if(count($findStok) > 0){
                    $stokAwal = $findStok->stok_akhir;
                }
				
                $mutasi = new Mutasi();
                $mutasi->id_barang = $post['idbarang'][$i];
				$mutasi->id_gudang = $model->id_gudang;
                $mutasi->kredit  = $post['jumlah'][$i];
                $mutasi->tanggal = $model->tanggal;
                $mutasi->stok_awal = $stokAwal;
                $mutasi->stok_akhir = $stokAwal - $post['jumlah'][$i];
                $mutasi->keterangan = 'Return dari No Faktur '.$post['no_faktur'][$i];
				$mutasi->record_date = new \yii\db\Expression('NOW()');
                $mutasi->update_date = new \yii\db\Expression('NOW()');
                $mutasi->date_stamp = new \yii\db\Expression('NOW()');
                $mutasi->record_by = Yii::$app->user->identity->id;
                $mutasi->update_by = Yii::$app->user->identity->id;
                $mutasi->save();
                $query = Yii::$app->db->createCommand("UPDATE stok_gudang SET 
						stok=stok - ".$post['jumlah'][$i]." , date_stamp = ".new \yii\db\Expression('NOW()')."						
						WHERE id_barang='".$post['idbarang'][$i]."' AND id_gudang='".$model->id_gudang."' ")->execute();
            } else {
                $data['pembelian'][$i] = $model->getErrors();
            }
        }
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $data;
    }

    public function actionUpdate($id)
    {
		// $privilage = Yii::$app->user->identity->privilage;
	    // if($privilage !== 1 && $privilage !== 3 && $privilage !== 5 ){
		    // throw new ForbiddenHttpException("Forbidden access");
	    // }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             \Yii::$app->getSession()->setFlash('status', 'true');
			
				if($model->save()){
				\Yii::$app->getSession()->setFlash('status', 'true');
				} else {
				\Yii::$app->getSession()->setFlash('status', 'false');
				}
				$model = new ReturPembelian();
					return $this->render('create', [
					'model' => $model,
					]);
			
        } else {
			\Yii::$app->getSession()->setFlash('status', '');
			if ($model->load(Yii::$app->request->post())){
				\Yii::$app->getSession()->setFlash('status', 'false');
			}
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
	
    public function actionAddretur()
    {
			$data = array();
			// $model = $this->findModel($_POST['idPembelian']);

			$model = DetailPembelian::find()
                ->joinWith(['pembelian'])
				->where([
				    'detail_pembelian.id' => $_POST['id']
                ])
                ->one();
			
			$tr = "<tr id=\"".$model->id."\" val=\"".$model->barang->nama."\">						
				<td>
					".$model->barang->kode."
					<input name=\"id[]\" value=\"".$model->id."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"id_gudang[]\" value=\"".$model->pembelian->id_gudang."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"id_pembelian[]\" value=\"".$model->id_pembelian."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"idbarang[]\" value=\"".$model->id_barang."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"namaproduk[]\" value=\"".$model->barang->nama."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"jumlah[]\" value=\"".$_POST['amountRetur']."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"hb[]\" value=\"".$model->harga_beli."\" type=\"hidden\" readonly=\"true\" />
					<input name=\"no_faktur[]\" value=\"".$model->pembelian->no_faktur."\" type=\"hidden\" readonly=\"true\" />

modules/pembelian/views/retur-pembelian/_form.bak.php
<?php

use app\models\Pembelian;
use kartik\grid\GridView;
use kartik\growl\Growl;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php
if (Yii::$app->session->getFlash('status') == 'true') {
    echo Growl::widget([
        'type' => Growl::TYPE_SUCCESS,
        'icon' => 'glyphicon glyphicon-ok-sign',
        'title' => 'Notifications',
        'showSeparator' => true,
        'body' => 'Data retur pembelian berhasil Ditambahkan',
        'pluginOptions' => [
            'showProgressbar' => false,
            'placement' => [
                'from' => 'bottom',
                'align' => 'right',
            ]
        ]
    ]);
} else if (Yii::$app->session->getFlash('status') == 'false') {
    echo Growl::widget([
        'type' => Growl::TYPE_DANGER,
        'icon' => 'glyphicon glyphicon-ok-sign',
        'title' => 'Notifications',
        'showSeparator' => true,
        'body' => 'Data retur pembelian gagal Ditambahkan',
        'pluginOptions' => [
            'showProgressbar' => false,
            'placement' => [
                'from' => 'bottom',
                'align' => 'right',
            ]
        ]
    ]);
}
?>

    <div class="col-md-12">


        <div class="widget">
            <div class="widget-header transparent">
                <div class="additional-btn">
                    <a href="#" class="hidden reload"><i class="icon-ccw-1"></i></a>
                    <a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>
                </div>
            </div>

            <div class="widget-content padding">
                <div class="retur-pembelian-form">

                    <?php $form = ActiveForm::begin([
                        'id' => 'mainForm'
                    ]); ?>

                    <div class="col-md-6">
                        <!--?= $form->field($model, 'no_faktur_pembelian')->dropDownList(ArrayHelper::map(Pembelian::find()->orderBy('no_faktur ASC')->groupBy('no_faktur')->all(),'no_faktur','no_faktur'),['prompt'=>'-- Pilih Faktur Pembelian --']); ?-->

                        <?php
                        $data = ArrayHelper::map(Pembelian::find()->orderBy('no_faktur ASC')->groupBy('no_faktur')->all(), 'no_faktur', 'no_faktur');
                        echo $form->field($model, 'no_faktur_pembelian')->widget(Select2::classname(), [
                            'data' => $data,
                            'options' => ['placeholder' => '--Pilih Faktur Pembelian--'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                        ]);
                        ?>

                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <?= Html::submitButton($model->isNewRecord ? 'Tampilkan' : 'Perbaharui', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

                            &nbsp;

                            <?= Html::a('Kembali', ['index'], ['class' => 'btn btn-danger']) ?>

                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>

                    <?php
                    if (isset($_POST['ReturPembelian'])){

                    ?>

                    <div class="col-md-12">
                        <h3>No Faktur: <?= $_POST['ReturPembelian']['no_faktur_pembelian'] ?></h3>
                    </div>
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <?php \yii\widgets\Pjax::begin([
                                'enablePushState' => false
                            ]); ?>
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                /*'filterModel' => $searchModel,*/
                                'columns' => [
                                    ['class' => 'kartik\grid\SerialColumn'],
                                    //'no_faktur',
                                    ['attribute' => 'id_barang',
                                        'label' => 'Kode Produk',
                                        'value' => 'barang.kode'],
                                    ['attribute' => 'id_barang',
                                        'label' => 'Nama Produk',
                                        'value' => 'barang.nama'],
                                    'jumlah',
                                    [
                                        'attribute' => 'harga_beli',
                                        'value' => function ($data) {
                                            return number_format($data->harga_beli, 2, ',', '.');
                                        }
                                    ],
                                    [
                                        'attribute' => 'diskon',
                                        'value' => function ($data) {
                                            return number_format($data->diskon, 2, ',', '.');
                                        }
                                    ],
                                    ['attribute' => 'ppn',
                                        'label' => 'PPN',
                                        'value' => function ($data) {
                                            return number_format($data->ppn, 2, ',', '.');
                                        }],
                                    [
                                        'attribute' => 'harga_kena_pajak',
                                        'label' => 'Harga Total',
                                        'value' => function ($data) {
                                            return number_format($data->harga_kena_pajak, 2, ',', '.');
                                        }
                                    ],
                                    [
                                        'label' => 'Total',
                                        'value' => function ($data) {
                                            return number_format((($data->ppn * $data->jumlah) + ($data->jumlah * ($data->harga_beli - $data->diskon))), 2, ',', '.');
                                        }],

                                    [
                                        'format' => 'raw',
                                        'value' => function ($data) {
                                            return Html::button('Retur', [
                                                'class' => 'btn btn-success retur btn-sm md-trigger',
                                                'data-id' => $data->id,
                                                'data-idPembelian' => $data->id_pembelian,
                                                'data-total' => $data->jumlah,
                                                'data-modal' => 'md-3d-slit']);
                                        }
                                    ],
                                ],
                            ]); ?>

                            <?php \yii\widgets\Pjax::end();
                            }

                            ?>
                        </div>
                    </div>
                    <div class="widget-content padding">
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!--
    <div class="col-md-12">
    <div class="card bg-white">
    <div class="card-block">
	
    <div class="barang-index">
        <div class="widget">
            <div class="widget-header transparent">
                <div class="additional-btn">
                    <a href="#" class="hidden reload"><i class="icon-ccw-1"></i></a>
                    <a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>
                </div>
            </div>
			
            <div class="widget-content padding">
                <?php $form = ActiveForm::begin([
                    'id' => 'returForm'
                ]); ?>

                <div class="form-group">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>
                                SKU
                            </th>
                            <th>
                                Produk
                            </th>
                            <th>
                                Jumlah
                            </th>
                            <th>
                                HPP
                            </th>
                            <th>
                                Diskon
                            </th>
                            <th>
                                PPN
                            </th>
                            <th>
                                Harga
                            </th>
                            <th>
                                Total
                            </th>
                            <th class="col-md-1">

                            </th>
                        </tr>
                        </thead>
                        <tbody id="tbody">
                        </tbody>
                    </table>
                </div>
                <button class="btn btn-success md-close" id="save">Save</button>
                <?php ActiveForm::end(); ?>

            </div>
			
        </div>
    </div>
-->

<?php
$script = <<< JS

	var addpenjualan = [];	
	$("#addbutton").attr('disabled',true);
	
	$("body").on('click','.remove', function(e){
		$(this).closest('tr').remove();
		var removeItem = $(this).closest('tr').attr('id');

		$('#grand_total').val(grand_total);
		delete addpenjualan[removeItem];

		$("#addbutton").fadeIn();
	});
		
	$("#addRetur").on('click', function(e){
		e.preventDefault();
		var form = $('#returForm').serialize();
		$.ajax({
			type: "POST",
			url: baseUrl+'pembelian/retur-pembelian/addretur',
			dataType: 'json',
			cache: false,
			data: form,
			success: function (json) {
				if(json.status){	
					$("#tbody").append(json.tr);	
					$('#md-id').val('');
					$('#md-total').val('');
									
				} else {
					
				}
			},
			error: function (xhr, ajaxOptions, thrownError) {
				console.log(xhr.status);
				console.log(xhr.responseText);
				console.log(thrownError);
			}
		});
	});	
	
	$("#save").on('click', function(e){
		e.preventDefault();
		var form = $('#returForm').serialize();
		$.ajax({
			type: "POST",
			url: baseUrl+'retur-pembelian/save',
			dataType: 'json',
			cache: false,
			data: form,
			success: function (json) {
				if(json.status){
					$( '#returForm' ).each(function(){
						this.reset();
					});
					addpenjualan = [];	
					$('#tbody').html('');
				} else {
					bootbox.alert("Failed to save!");
				}
			},
			error: function (xhr, ajaxOptions, thrownError) {
				console.log(xhr.status);
				console.log(xhr.responseText);
				console.log(thrownError);
			}
		});
	});	

	$('body').on('click', '.retur', function(e){
	   e.preventDefault(); 
	   var thisRow = $(this);
	   bootbox.prompt({
            title: "Masukkan jumlah yang di retur",
            inputType: 'number',
            callback: function (result) {
                console.log(result+' - '+thisRow.attr('data-id'));
                $.ajax({
                    type: "POST",
                    url: baseUrl+'retur-pembelian/addretur',
                    dataType: 'json',
                    cache: false,
                    data: {
                        'id':thisRow.attr('data-id'),
                        'amountRetur':result,
                    },
                    success: function (json) {
                        if(json.status){
                            $("#tbody").append(json.tr);
                        } else {
                            
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        console.log(xhr.status);
                        console.log(xhr.responseText);
                        console.log(thrownError);
                    }
                });
            }
        });
	});

JS;
$this->registerJs($script, \yii\web\View::POS_READY);
?>

modules/pembelian/views/retur-pembelian/_nota.php
<?php
use app\models\ReturPembelian;
use app\models\Pembelian;

$returPembelian = ReturPembelian::find()
    ->where([
        'id_pembelian' => $id,
        'no_faktur_pembelian' => $faktur,
        'tanggal_retur' => date('Y-m-d', strtotime($tanggal))
    ])
    ->all();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" media="print" href="<?= $this->theme->baseUrl ?>/styles/print.css">
    <link rel="stylesheet" media="print" href="<?= $this->theme->baseUrl ?>/vendor/bootstrap/dist/css/bootstrap.css">
</head>
<body id="nota">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td colspan="3" align="center"><h3>Bukti Retur Pembelian</h3></td>
    </tr>
</table>
<table width="100%" border="1" cellpadding="0" cellspacing="0" class="table table-bordered">
    <thead>
    <tr class="success">
        <th>No</th>
        <th>Tanggal</th>>
        <th>Gudang</th>
        <th>No. Faktur</th>
        <th>Barang</th>
        <th>Jumlah</th>
        <th>Harga Beli</th>
        <th>Diskon</th>
        <th>PPN</th>
        <th>Harga PPN</th>
        <th>Total</th>
    </tr>
    </thead>
    <tbody id="paddingLess">

    <?php
    $i = 0;
    foreach($returPembelian as $row) {
        $i++;
        ?>
        <tr class="success">
            <td style="text-align: center;"><?= $i ?></td>
            <td><?= date('Y-m-d', strtotime($row->tanggal_retur))?></td>
            <td><?= $row->gudang->nama?> </td>
            <td style="text-align: center;"><?= $row->no_faktur_pembelian ?></td>
            <td><?= $row->barang->nama ?></td>
            <td style="text-align: center;"><?= $row->jumlah ?></td>
            <td style="text-align: right;"><?= is_numeric($row->harga_beli)?number_format($row->harga_beli):'0' ?></td>
            <td style="text-align: right;"><?= is_numeric($row->diskon)?number_format($row->diskon):'0' ?></td>
            <td style="text-align: right;"><?= is_numeric($row->ppn)?number_format($row->ppn):'0' ?></td>
            <td style="text-align: right;"><?= is_numeric($row->harga_kena_pajak)?number_format($row->harga_kena_pajak):'0' ?></td>
            <td style="text-align: right;"><?= is_numeric($row->total)?number_format($row->total):'0' ?></td>
        </tr>
    <?php }?>
    </tbody>

</table>
<script src="<?= $this->theme->baseUrl ?>/vendor/jquery/dist/jquery.js"></script>
<script src="<?= $this->theme->baseUrl ?>/vendor/bootstrap/dist/js/bootstrap.js"></script>
</body>
</html>

modules/pembelian/views/retur-pembelian/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ReturPembelianSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="retur-pembelian-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'no_faktur_pembelian') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/pembelian/views/retur-pembelian/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ReturPembelian */

$this->title = 'Tambah Retur Pembelian';
$this->params['breadcrumbs'][] = ['label' => 'Retur Pembelian', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- Page Heading Start -->
	<div class="page-heading">
	  <h4><i class='fa fa-check-square'></i> Penambahan Retur Pembelian</h4>
	</div>
	<div class="card bg-white">
	<div class="card-header">
	</div>
	<div class="card-block">
<div class="barang-index">
<!-- Page Heading End-->

<div class="widget-content padding">
	<div class="row">
		<?= $this->render('_form', [
			'model' => $model,
			'dataProvider'=>$dataProvider
		]) ?>
	</div>
</div>

modules/pembelian/views/retur-pembelian/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\ReturPembelianSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Retur Pembelian';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-heading">
	<h1><i class='fa fa-table'></i> Daftar Retur Pembelian</h1>
	<h3>Retur Pembelian Obat</h3>            
</div>

<div class="widget">
	<div class="widget-header transparent">
		<div class="additional-btn">
			<a href="#" class="hidden reload"><i class="icon-ccw-1"></i></a>
			<a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>
			
		</div>
	</div>

	<div class="widget-content padding">

<div class="retur-pembelian-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('New Retur Pembelian', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<!--
	<?php
		Pjax::begin(['timeout'=>10000,'clientOptions'=>['container'=>'Pjax-container']]);
	?>
	
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'no_faktur_pembelian',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

	<?php
	Pjax::End();
?>
-->
	
</div>
</div>
	</div>
</div>

modules/pembelian/views/retur-pembelian/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ReturPembelian */

$this->title = 'Perbaharui Retur Pembelian: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Retur Pembelian', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<!-- Page Heading Start -->
	<div class="page-heading">
	  <h1><i class='fa fa-check-square'></i> Perbaharui Retur Pembelian</h1>
	</div>
<!-- Page Heading End-->

<div class="widget-content padding">
	<div class="row">
		<div class="col-md-12">
			<?= $this->render('_form', [
			'model' => $model,
		]) ?>

		</div>
	</div>
</div>

modules/pembelian/views/retur-pembelian/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ReturPembelian */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Retur Pembelian', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="page-heading">
	  <h1></i> <?= Html::encode($this->title) ?></h1>
</div>

<div class="widget">
	<div class="widget-header transparent">
		<div class="additional-btn">
			<a href="#" class="hidden reload"><i class="icon-ccw-1"></i></a>
			<a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>
			
		</div>
	</div>

	<div class="widget-content padding">

<div class="retur-pembelian-view">

    <p>
        <?= Html::a('Perbaharui', ['update', 'id' => $model->id], ['class' => 'btn btn-blue-2']) ?>
		&nbsp;
        <?= Html::a('Hapus', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-red-1',
            'data' => [
                'confirm' => 'Apa anda yakin akan menghapus data ini?',
                'method' => 'post',
            ],
        ]) ?>
		&nbsp;
		<?= Html::a('Tambah Retur Pembelian', ['create'], ['class' => 'btn btn-green-3']) ?>
		&nbsp;
		<?= Html::a('Data Retur Pembelian', ['index'], ['class' => 'btn btn-info']) ?>
    </p>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'no_faktur_pembelian',
        ],
    ]) ?>

</div>
</div>
</div>
</div>